In [11]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

pd.set_option('display.max_columns', 100)
df = pd.read_csv('https://query.data.world/s/uikepcpffyo2nhig52xxeevdialfl7')
df.head()

,Unnamed: 0,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,Ratings.Source,Ratings.Value,Metascore,imdbRating,imdbVotes,imdbID,Type,tomatoMeter,tomatoImage,tomatoRating,tomatoReviews,tomatoFresh,tomatoRotten,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,1,The Shawshank Redemption,1994,R,14 Oct 1994,142 min,"Crime, Drama",Frank Darabont,"Stephen King (short story ""Rita Hayworth and S...","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,English,USA,Nominated for 7 Oscars. Another 19 wins & 30 n...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.3/10,80.0,9.3,"1,825,626",tt0111161,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/shawshank_rede...,27 Jan 1998,NaN,Columbia Pictures,NaN,True
1,2,The Godfather,1972,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"Mario Puzo (screenplay), Francis Ford Coppola ...","Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,"English, Italian, Latin",USA,Won 3 Oscars. Another 23 wins & 27 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.2/10,100.0,9.2,"1,243,444",tt0068646,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather/,09 Oct 2001,NaN,Paramount Pictures,http://www.thegodfather.com,True
2,3,The Godfather: Part II,1974,R,20 Dec 1974,202 min,"Crime, Drama",Francis Ford Coppola,"Francis Ford Coppola (screenplay), Mario Puzo ...","Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...,"English, Italian, Spanish, Latin, Sicilian",USA,Won 6 Oscars. Another 10 wins & 20 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,85.0,9.0,"856,870",tt0071562,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather_part...,24 May 2005,NaN,Paramount Pictures,http://www.thegodfather.com/,True
3,4,The Dark Knight,2008,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...,"English, Mandarin","USA, UK",Won 2 Oscars. Another 151 wins & 153 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,82.0,9.0,"1,802,351",tt0468569,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knight/,09 Dec 2008,"$533,316,061",Warner Bros. Pictures/Legendary,http://thedarkknight.warnerbros.com/,True
4,5,12 Angry Men,1957,APPROVED,01 Apr 1957,96 min,"Crime, Drama",Sidney Lumet,"Reginald Rose (story), Reginald Rose (screenplay)","Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...,English,USA,Nominated for 3 Oscars. Another 16 wins & 8 no...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,8.9/10,96.0,8.9,"494,215",tt0050083,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/1000013-12_ang...,06 Mar 2001,NaN,Criterion Collection,http://www.criterion.com/films/27871-12-angry-men,True

In [12]:
df.shape

(250, 38)

In [13]:
df = df[['Title','Genre','Director','Actors','Plot']]
df.head()

,Title,Genre,Director,Actors,Plot
0,The Shawshank Redemption,"Crime, Drama",Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...
1,The Godfather,"Crime, Drama",Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...
2,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,"Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...
3,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...
4,12 Angry Men,"Crime, Drama",Sidney Lumet,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...

In [14]:
# discarding the commas between the actors' full names and getting only the first three names
df['Actors'] = df['Actors'].map(lambda x: x.split(',')[:3])

In [15]:
df['Actors']

0            [Tim Robbins,  Morgan Freeman,  Bob Gunton]
1               [Marlon Brando,  Al Pacino,  James Caan]
2             [Al Pacino,  Robert Duvall,  Diane Keaton]
3        [Christian Bale,  Heath Ledger,  Aaron Eckhart]
4           [Martin Balsam,  John Fiedler,  Lee J. Cobb]
                             ...
245           [Ray Milland,  Jane Wyman,  Phillip Terry]
246    [Brie Larson,  John Gallagher Jr.,  Stephanie ...
247      [Cary Grant,  Rosalind Russell,  Ralph Bellamy]
248    [Sissy Spacek,  Jane Galloway Heitz,  Joseph A...
249           [Dev Patel,  Saurabh Shukla,  Anil Kapoor]
Name: Actors, Length: 250, dtype: object

In [16]:
# putting the genres in a list of words
df['Genre'] = df['Genre'].map(lambda x: x.lower().split(','))

In [17]:
df['Genre']

0                 [crime,  drama]
1                 [crime,  drama]
2                 [crime,  drama]
3        [action,  crime,  drama]
4                 [crime,  drama]
                  ...
245           [drama,  film-noir]
246                       [drama]
247    [comedy,  drama,  romance]
248           [biography,  drama]
249                       [drama]
Name: Genre, Length: 250, dtype: object

In [18]:
df['Director'] = df['Director'].map(lambda x: x.split(' '))

In [19]:
df['Director']

0                      [Frank, Darabont]
1               [Francis, Ford, Coppola]
2               [Francis, Ford, Coppola]
3                   [Christopher, Nolan]
4                        [Sidney, Lumet]
                     ...
245                      [Billy, Wilder]
246            [Destin, Daniel, Cretton]
247                      [Howard, Hawks]
248                       [David, Lynch]
249    [Danny, Boyle,, Loveleen, Tandan]
Name: Director, Length: 250, dtype: object

In [20]:
for index, row in df.iterrows():
    row['Actors'] = [x.lower().replace(' ','') for x in row['Actors']]
    row['Director'] = ''.join(row['Director']).lower()

In [21]:
df['Actors']

0                 [timrobbins, morganfreeman, bobgunton]
1                    [marlonbrando, alpacino, jamescaan]
2                  [alpacino, robertduvall, dianekeaton]
3             [christianbale, heathledger, aaroneckhart]
4                 [martinbalsam, johnfiedler, leej.cobb]
                             ...
245                [raymilland, janewyman, phillipterry]
246     [brielarson, johngallagherjr., stephaniebeatriz]
247           [carygrant, rosalindrussell, ralphbellamy]
248    [sissyspacek, janegallowayheitz, josepha.carpe...
249                [devpatel, saurabhshukla, anilkapoor]
Name: Actors, Length: 250, dtype: object

In [22]:
df['Director']

0                  frankdarabont
1             francisfordcoppola
2             francisfordcoppola
3               christophernolan
4                    sidneylumet
                 ...
245                  billywilder
246          destindanielcretton
247                  howardhawks
248                   davidlynch
249    dannyboyle,loveleentandan
Name: Director, Length: 250, dtype: object

In [26]:
from rake_nltk import Rake

In [27]:
# initializing the new column
df['Key_words'] = ""

for index, row in df.iterrows():
    plot = row['Plot']
    
    # instantiating Rake, by default is uses english stopwords from NLTK
    # and discard all puntuation characters
    r = Rake()

    # extracting the words by passing the text
    r.extract_keywords_from_text(plot)

    # getting the dictionary whith key words and their scores
    key_words_dict_scores = r.get_word_degrees()
    
    # assigning the key words to the new column
    row['Key_words'] = list(key_words_dict_scores.keys())

# dropping the Plot column
df.drop(columns = ['Plot'], inplace = True)

In [28]:
key_words_dict_scores

defaultdict(<function rake_nltk.rake.Rake._build_word_co_occurance_graph.<locals>.<lambda>()>,
            {'cheating': 1,
             'mumbai': 3,
             'teen': 3,
             'reflects': 3,
             'accused': 1,
             'wants': 1,
             'slums': 1,
             'indian': 2,
             'version': 2,
             'upbringing': 1,
             'millionaire': 2,
             '?"': 2})

In [29]:
df.set_index('Title', inplace = True)
df.head()

,Genre,Director,Actors,Key_words
Title,,,,
The Shawshank Redemption,"[crime, drama]",frankdarabont,"[timrobbins, morganfreeman, bobgunton]","[two, imprisoned, men, bond, eventual, redempt..."
The Godfather,"[crime, drama]",francisfordcoppola,"[marlonbrando, alpacino, jamescaan]","[clandestine, empire, organized, crime, dynast..."
The Godfather: Part II,"[crime, drama]",francisfordcoppola,"[alpacino, robertduvall, dianekeaton]","[expands, tightens, grip, portrayed, family, c..."
The Dark Knight,"[action, crime, drama]",christophernolan,"[christianbale, heathledger, aaroneckhart]","[joker, emerges, greatest, psychological, phys..."
12 Angry Men,"[crime, drama]",sidneylumet,"[martinbalsam, johnfiedler, leej.cobb]","[prevent, jury, holdout, attempts, forcing, re..."

In [30]:
df['bag_of_words'] = ''
columns = df.columns
for index, row in df.iterrows():
    words = ''
    for col in columns:
        if col != 'Director':
            words = words + ' '.join(row[col])+ ' '
        else:
            words = words + row[col]+ ' '
    row['bag_of_words'] = words
    
df.drop(columns = [col for col in df.columns if col!= 'bag_of_words'], inplace = True)

In [31]:
df.head()

                                                               bag_of_words
Title
The Shawshank Redemption  crime  drama frankdarabont timrobbins morganfr...
The Godfather             crime  drama francisfordcoppola marlonbrando a...
The Godfather: Part II    crime  drama francisfordcoppola alpacino rober...
The Dark Knight           action  crime  drama christophernolan christia...
12 Angry Men              crime  drama sidneylumet martinbalsam johnfied...

In [32]:
# instantiating and generating the count matrix
count = CountVectorizer()
count_matrix = count.fit_transform(df['bag_of_words'])

# creating a Series for the movie titles so they are associated to an ordered numerical
# list I will use later to match the indexes
indices = pd.Series(df.index)
indices[:5]

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                12 Angry Men
Name: Title, dtype: object

In [33]:
count_matrix

<250x2961 sparse matrix of type '<class 'numpy.int64'>'
	with 5342 stored elements in Compressed Sparse Row format>

In [34]:
c=count_matrix.todense()

In [35]:
c

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
type(count_matrix)

scipy.sparse.csr.csr_matrix

In [37]:
print(count_matrix[0,:])

  (0, 584)	1
  (0, 768)	1
  (0, 1011)	1
  (0, 2678)	1
  (0, 1810)	1
  (0, 306)	1
  (0, 2765)	1
  (0, 1269)	1
  (0, 1733)	1
  (0, 311)	1
  (0, 888)	1
  (0, 2174)	1
  (0, 969)	1
  (0, 2481)	1
  (0, 2950)	1
  (0, 59)	1
  (0, 1899)	1
  (0, 519)	1
  (0, 655)	1

In [38]:
count.vocabulary_

{'crime': 584,
 'drama': 768,
 'frankdarabont': 1011,
 'timrobbins': 2678,
 'morganfreeman': 1810,
 'bobgunton': 306,
 'two': 2765,
 'imprisoned': 1269,
 'men': 1733,
 'bond': 311,
 'eventual': 888,
 'redemption': 2174,
 'finding': 969,
 'solace': 2481,
 'years': 2950,
 'acts': 59,
 'number': 1899,
 'common': 519,
 'decency': 655,
 'francisfordcoppola': 1007,
 'marlonbrando': 1671,
 'alpacino': 118,
 'jamescaan': 1355,
 'clandestine': 475,
 'empire': 846,
 'organized': 1932,
 'dynasty': 793,
 'transfers': 2730,
 'control': 553,
 'aging': 82,
 'patriarch': 1972,
 'reluctant': 2193,
 'son': 2492,
 'robertduvall': 2264,
 'dianekeaton': 710,
 'expands': 908,
 'tightens': 2670,
 'grip': 1131,
 'portrayed': 2057,
 'family': 934,
 'syndicate': 2608,
 'michael': 1750,
 'early': 795,
 'life': 1575,
 '1920s': 8,
 'new': 1870,
 'york': 2953,
 'career': 391,
 'vito': 2854,
 'corleone': 563,
 'action': 56,
 'christophernolan': 464,
 'christianbale': 458,
 'heathledger': 1179,
 'aaroneckhart': 31,
 'joker': 1444,
 'emerges': 836,
 'greatest': 1127,
 'psychological': 2119,
 'physical': 2024,
 'tests': 2646,
 'dark': 625,
 'knight': 1508,
 'must': 1841,
 'accept': 41,
 'one': 1924,
 'mysterious': 1844,
 'past': 1966,
 'ability': 37,
 'people': 1991,
 'fight': 959,
 'injustice': 1298,
 'wreaks': 2943,
 'havoc': 1173,
 'chaos': 430,
 'gotham': 1113,
 'menace': 1734,
 'known': 1512,
 'sidneylumet': 2443,
 'martinbalsam': 1678,
 'johnfiedler': 1424,
 'leej': 1556,
 'cobb': 492,
 'prevent': 2079,
 'jury': 1471,
 'holdout': 1213,
 'attempts': 212,
 'forcing': 991,
 'reconsider': 2168,
 'evidence': 891,
 'colleagues': 499,
 'miscarriage': 1784,
 'justice': 1472,
 'biography': 290,
 'history': 1206,
 'stevenspielberg': 2545,
 'liamneeson': 1573,
 'benkingsley': 277,
 'ralphfiennes': 2144,
 'german': 1082,
 'world': 2935,
 'war': 2870,
 'ii': 1260,
 'oskar': 1938,
 'schindler': 2354,
 'gradually': 1117,
 'becomes': 257,
 'concerned': 532,
 'persecution': 1997,
 'occupied': 1910,
 'poland': 2048,
 'jewish': 1399,
 'workforce': 2932,
 'witnessing': 2920,
 'nazi': 1856,
 'germans': 1083,
 'adventure': 71,
 'fantasy': 938,
 'peterjackson': 2011,
 'noelappleby': 1888,
 'aliastin': 106,
 'seanastin': 2369,
 'gandalf': 1048,
 'army': 180,
 'sam': 2328,
 'gaze': 1061,
 'sauron': 2341,
 'approach': 172,
 'mount': 1816,
 'doom': 757,
 'aragorn': 174,
 'lead': 1544,
 'draw': 769,
 'ring': 2250,
 'frodo': 1032,
 'quentintarantino': 2131,
 'timroth': 2679,
 'amandaplummer': 124,
 'lauralovelace': 1534,
 'lives': 1592,
 'diner': 716,
 'bandits': 232,
 'intertwine': 1316,
 'pair': 1950,
 'wife': 2896,
 'boxer': 330,
 'four': 1003,
 'tales': 2614,
 'violence': 2847,
 'gangster': 1051,
 'mob': 1795,
 'hit': 1207,
 'davidfincher': 631,
 'edwardnorton': 816,
 'bradpitt': 335,
 'meatloaf': 1715,
 'much': 1826,
 'underground': 2783,
 'club': 488,
 'looking': 1607,
 'evolves': 893,
 'way': 2877,
 'may': 1707,
 'change': 428,
 'something': 2489,
 'insomniac': 1304,
 'office': 1914,
 'worker': 2931,
 'care': 390,
 'soap': 2477,
 'maker': 1644,
 'forming': 998,
 'devil': 702,
 'crosses': 594,
 'paths': 1969,
 'alanhoward': 90,
 'destroy': 689,
 'journey': 1462,
 'powerful': 2069,
 'save': 2343,
 'middle': 1768,
 'earth': 796,
 'eight': 822,
 'companions': 522,
 'set': 2406,
 'meek': 1722,
 'hobbit': 1210,
 'lord': 1609,
 'shire': 2432,
 'comedy': 511,
 'romance': 2289,
 'robertzemeckis': 2275,
 'tomhanks': 2686,
 'rebeccawilliams': 2164,
 'sallyfield': 2326,
 'present': 2077,
 'true': 2751,
 'love': 1614,
 'jenny': 1390,
 'curran': 600,
 'intelligent': 1311,
 'accidentally': 45,
 'many': 1658,
 'historic': 1205,
 'moments': 1800,
 'eludes': 832,
 'forrest': 1000,
 'gump': 1141,
 'irvinkershner': 1334,
 'markhamill': 1668,
 'harrisonford': 1167,
 'carriefisher': 399,
 'darth': 628,
 'vader': 2815,
 'hunts': 1250,
 'questionable': 2133,
 'ally': 115,
 'newly': 1872,
 'established': 880,
 'base': 245,
 'rebels': 2165,
 'friends': 1030,
 'shelter': 2427,
 'capture': 387,
 'luke': 1622,
 'overpowered': 1944,
 'skywalker': 2466,
 'begins': 264,
 'jedi': 1385,
 'training': 2728,
 'plan': 2033,
 'master': 1689,
 'yoda': 2952,
 'sci': 2357,
 'fi': 956,
 'leonardodicaprio': 1566,
 'josephgordon': 1457,
 'levitt': 1569,
 'ellenpage': 831,
 'given': 1097,
 'ceo': 423,
 'use': 2810,
 'thief': 2654,
 'dream': 771,
 'planting': 2038,
 'mind': 1782,
 'idea': 1255,
 'steals': 2535,
 'corporate': 564,
 'secrets': 2382,
 'sharing': 2419,
 'technology': 2625,
 'inverse': 1318,
 'task': 2619,
 'bruceallpress': 355,
 'johnbach': 1418,
 'saruman': 2339,
 'stand': 2522,
 'isengard': 1335,
 'shifty': 2430,
 'gollum': 1109,
 'help': 1187,
 'edge': 802,
 'closer': 486,
 'divided': 741,
 'fellowship': 953,
 'makes': 1645,
 'mordor': 1809,
 'hordes': 1224,
 'milosforman': 1781,
 'michaelberryman': 1753,
 'peterbrocco': 2009,
 'deanr': 646,
 'brooks': 351,
 'rallies': 2142,
 'criminal': 586,
 'pleads': 2042,
 'insanity': 1301,
 'trouble': 2749,
 'mental': 1736,
 'institution': 1307,
 'oppressive': 1929,
 'nurse': 1900,
 'scared': 2349,
 'patients': 1971,
 'getting': 1089,
 'martinscorsese': 1680,
 'robertdeniro': 2262,
 'rayliotta': 2154,
 'joepesci': 1415,
 'henry': 1191,
 'hill': 1202,
 'teen': 2626,
 'covering': 574,
 'italian': 1339,
 'american': 127,
 'partners': 1963,
 'jimmy': 1401,
 'conway': 559,
 'relationship': 2188,
 'story': 2551,
 'tommy': 2694,
 'devitto': 703,
 'mafia': 1634,
 'karen': 1476,
 'lanawachowski': 1520,
 'lillywachowski': 1579,
 'keanureeves': 1484,
 'laurencefishburne': 1536,
 'carrie': 397,
 'annemoss': 151,
 'role': 2287,
 'controllers': 554,
 'reality': 2160,
 'nature': 1853,
 'computer': 530,
 'hacker': 1151,
 'learns': 1550,
 'georgelucas': 1076,
 'evil': 892,
 'destroying': 690,
 'battle': 250,
 'also': 119,
 'attempting': 211,
 'rescue': 2207,
 'princess': 2085,
 'leia': 1564,
 'cocky': 493,
 'pilot': 2027,
 'galaxy': 1043,
 'joins': 1443,
 'forces': 990,
 'wookiee': 2929,
 'droids': 778,
 'station': 2532,
 'mystery': 1845,
 'andrewkevinwalker': 138,
 'kevinspacey': 1493,
 'seven': 2410,
 'deadly': 642,
 'sins': 2457,
 'hunt': 1247,
 'detectives': 696,
 'veteran': 2827,
 'uses': 2811,
 'serial': 2402,
 'killer': 1497,
 'motives': 1815,
 'rookie': 2296,
 'frankcapra': 1010,
 'jamesstewart': 1364,
 'donnareed': 754,
 'lionelbarrymore': 1588,
 'showing': 2439,
 'sent': 2398,
 'desperately': 686,
 'frustrated': 1034,
 'businessman': 370,
 'angel': 141,
 'would': 2941,
 'like': 1576,
 'heaven': 1180,
 'never': 1869,
 'existed': 906,
 'thriller': 2666,
 'jonathandemme': 1446,
 'jodiefoster': 1411,
 'lawrencea': 1542,
 'bonney': 312,
 'kasilemmons': 1480,
 'incarcerated': 1274,
 'cadet': 374,
 'confide': 537,
 'catching': 413,
 'another': 155,
 'young': 2954,
 'skins': 2465,
 'manipulative': 1654,
 'victims': 2831,
 'receive': 2166,
 'bryansinger': 359,
 'stephenbaldwin': 2538,
 'gabrielbyrne': 1042,
 'beniciodeltoro': 276,
 'twisty': 2764,
 'events': 887,
 'leading': 1546,
 'boat': 302,
 'began': 262,
 'horrific': 1225,
 'gun': 1142,
 'sole': 2485,
 'survivor': 2600,
 'tells': 2631,
 'seemingly': 2387,
 'random': 2147,
 'police': 2049,
 'lineup': 1586,
 'five': 976,
 'criminals': 588,
 'met': 1746,
 'lucbesson': 1620,
 'jeanreno': 1384,
 'garyoldman': 1056,
 'natalieportman': 1852,
 'protégée': 2115,
 'old': 1920,
 'girl': 1095,
 'mathilda': 1695,
 'form': 996,
 'unusual': 2799,
 'reluctantly': 2194,
 'taken': 2610,
 'professional': 2101,
 'assassin': 195,
 'léon': 1626,
 'murdered': 1831,
 'trade': 2722,
 'year': 2949,
 '12': 3,
 'tomsizemore': 2696,
 'edwardburns': 812,
 'normandy': 1891,
 'landings': 1523,
 'killed': 1496,
 'soldiers': 2484,
 'go': 1104,
 'behind': 266,
 'enemy': 853,
 'lines': 1585,
 'group': 1133,
 'retrieve': 2218,
 'following': 984,
 'paratrooper': 1956,
 'whose': 2894,
 'brothers': 353,
 'charleschaplin': 437,
 'virginiacherrill': 2849,
 'florencelee': 978,
 'harrymyers': 1170,
 'medically': 1720,
 'aid': 86,
 'eyed': 919,
 'tramp': 2729,
 'fallen': 930,
 'dewy': 706,
 'sightless': 2445,
 'flower': 979,
 'accumulates': 48,
 'money': 1802,
 'wealthy': 2879,
 'erratic': 875,
 'tippler': 2680,
 'able': 38,
 'ellenburstyn': 829,
 'matthewmcconaughey': 1701,
 'mackenziefoy': 1628,
 'ensure': 865,
 'humanity': 1241,
 'space': 2499,
 'survival': 2596,
 'explorers': 915,
 'travel': 2735,
 'attempt': 210,
 'team': 2623,
 'wormhole': 2936,
 'tonykaye': 2701,
 'edwardfurlong': 814,
 'beverlyd': 282,
 'angelo': 143,
 'wrong': 2946,
 'path': 1967,
 'younger': 2955,
 'brother': 352,
 'former': 997,
 'neo': 1866,
 'skinhead': 2464,
 'tries': 2746,
 'going': 1107,
 'paulettegoddard': 1977,
 'henrybergman': 1192,
 'homeless': 1220,
 'woman': 2924,
 'live': 1591,
 'struggles': 2564,
 'modern': 1796,
 'industrial': 1281,
 'society': 2480,
 'michaelcurtiz': 1758,
 'humphreybogart': 1245,
 'ingridbergman': 1296,
 'paulhenreid': 1980,
 'cynical': 607,
 'expatriate': 909,
 'encounters': 850,
 'lover': 1616,
 'casablanca': 407,
 'unforeseen': 2786,
 'complications': 529,
 'december': 654,
 '1941': 11,
 'davidmorse': 634,
 'michaelclarkeduncan': 1757,
 'affected': 75,
 'black': 295,
 'man': 1648,
 'accused': 50,
 'child': 447,
 'murder': 1830,
 'gift': 1093,
 'guards': 1138,
 'yet': 2951,
 'death': 647,
 'row': 2300,
 'charges': 434,
 'rape': 2148,
 'horror': 1226,
 'alfredhitchcock': 104,
 'anthonyperkins': 160,
 'veramiles': 2822,
 'johngavin': 1429,
 'mother': 1814,
 '40': 28,
 'domination': 751,
 '000': 0,
 'employer': 847,
 'client': 481,
 'goes': 1106,
 'checks': 444,
 'phoenix': 2021,
 'secretary': 2381,
 'embezzles': 835,
 'remote': 2199,
 'motel': 1813,
 'run': 2306,
 'karenallen': 1477,
 'paulfreeman': 1978,
 'nazis': 1857,
 'archaeologist': 175,
 'adventurer': 72,
 'indiana': 1279,
 'jones': 1448,
 'find': 968,
 'government': 1114,
 'covenant': 572,
 'hired': 1203,
 'ark': 179,
 'music': 1837,
 'romanpolanski': 2290,
 'adrienbrody': 68,
 'emiliafox': 838,
 'michalzebrowski': 1764,
 'polish': 2051,
 'musician': 1839,
 'survive': 2597,
 'destruction': 692,
 'warsaw': 2874,
 'ghetto': 1090,
 'gracekelly': 1116,
 'wendellcorey': 2887,
 'committed': 518,
 'convinced': 558,
 'wheelchair': 2891,
 'apartment': 169,
 'window': 2912,
 'bound': 324,
 'photographer': 2022,
 'spies': 2509,
 'neighbours': 1863,
 'mattdamon': 1696,
 'jacknicholson': 1346,
 'infiltrating': 1287,
 'irish': 1332,
 'gang': 1050,
 'undercover': 2781,
 'cop': 560,
 'mole': 1798,
 'south': 2498,
 'boston': 322,
 'identify': 1257,
 'damienchazelle': 614,
 'milesteller': 1774,
 'simmons': 2451,
 'paulreiser': 1982,
 'nothing': 1895,
 'potential': 2065,
 'stop': 2549,
 'promising': 2108,
 'drummer': 781,
 'enrolls': 862,
 'dreams': 772,
 'greatness': 1128,
 'throat': 2667,
 'conservatory': 549,
 'realize': 2161,
 'student': 2568,
 'mentored': 1739,
 'cut': 603,
 'instructor': 1308,
 'jamescameron': 1356,
 'arnoldschwarzenegger': 181,
 'lindahamilton': 1581,
 'john': 1417,
 'connor': 547,
 'cyborg': 605,
 'kill': 1495,
 'sarah': 2338,
 'advanced': 70,
 'ten': 2635,
 'protect': 2114,
 'failed': 927,
 'identical': 1256,
 'michaelj': 1760,
 'fox': 1004,
 'christopherlloyd': 463,
 'leathompson': 1551,
 '30': 27,
 'close': 485,
 'friend': 1029,
 'high': 1200,
 'school': 2355,
 'maverick': 1704,
 'scientist': 2358,
 'doc': 744,
 'brown': 354,
 'traveling': 2736,
 'delorean': 672,
 'invented': 1317,
 '17': 4,
 'time': 2673,
 'marty': 1683,
 'mcfly': 1711,
 'ridleyscott': 2246,
 'russellcrowe': 2312,
 'joaquinphoenix': 1409,
 'connienielsen': 546,
 'roman': 2288,
 'general': 1064,
 'gladiator': 1099,
 'comes': 512,
 'emperor': 845,
 'seek': 2384,
 'revenge': 2226,
 'betrayed': 280,
 'rome': 2291,
 'corrupt': 565,
 'animation': 148,
 'rogerallers': 2284,
 'robminkoff': 2278,
 'rowanatkinson': 2301,
 'matthewbroderick': 1699,
 'niketacalame': 1884,
 'identity': 1258,
 'testing': 2645,
 'boundaries': 325,
 'sometimes': 2490,
 'gets': 1088,
 'future': 1040,
 'king': 1502,
 'simba': 2450,
 'searches': 2376,
 'lion': 1587,
 'cub': 597,
 'penchant': 1988,
 'please': 2043,
 'others': 1939,
 'eagerness': 794,
 'hughjackman': 1238,
 'michaelcaine': 1755,
 'upmanship': 2803,
 'competitive': 526,
 'create': 579,
 'stage': 2520,
 'magicians': 1639,
 'engage': 854,
 'ultimate': 2771,
 'illusion': 1262,
 'martinsheen': 1681,
 'vietnam': 2840,
 'dangerous': 617,
 'mission': 1789,
 'cambodia': 379,
 'captain': 384,
 'willard': 2899,
 'god': 1105,
 'among': 131,
 'local': 1597,
 'tribe': 2742,
 'assassinate': 196,
 'renegade': 2200,
 'colonel': 505,
 'guypearce': 1149,
 'joepantoliano': 1414,
 'murderer': 1832,
 'obstacle': 1907,
 'short': 2435,
 'term': 2637,
 'memory': 1732,
 'loss': 1611,
 'juggles': 1467,
 'searching': 2377,
 'keeping': 1487,
 'jackoakie': 1347,
 'reginaldgardiner': 2184,
 'avoid': 222,
 'hynkel': 1254,
 'regime': 2183,
 'dictator': 712,
 'adenoid': 64,
 'expand': 907,
 'poor': 2055,
 'barber': 239,
 'film': 965,
 'noir': 1889,
 'billywilder': 289,
 'williamholden': 2904,
 'gloriaswanson': 1103,
 'erichvonstroheim': 872,
 'faded': 925,
 'silent': 2448,
 'star': 2527,
 'developing': 701,
 'script': 2366,
 'screenwriter': 2365,
 'rework': 2228,
 'tomskerritt': 2697,
 'sigourneyweaver': 2447,
 'veronicacartwright': 2824,
 'cycle': 606,
 'soon': 2493,
 'source': 2497,
 'moon': 1806,
 'finds': 970,
 'merely': 1743,
 'begun': 265,
 'crew': 583,
 'attacked': 208,
 'distress': 737,
 'call': 377,
 'unknown': 2793,
 'transmission': 2732,
 'landing': 1522,
 'merchant': 1741,
 'vessel': 2826,
 'perceives': 1993,
 'stanleykubrick': 2526,
 'petersellers': 2013,
 'georgec': 1073,
 'scott': 2360,
 'sterlinghayden': 2541,
 'room': 2297,
 'full': 1036,
 'generals': 1065,
 'frantically': 1017,
 'try': 2754,
 'insane': 1300,
 'triggers': 2747,
 'politicians': 2053,
 'nuclear': 1898,
 'holocaust': 1217,
 'kirkdouglas': 1505,
 'ralphmeeker': 2146,
 'adolphemenjou': 66,
 'cowardice': 575,
 'commanding': 515,
 'officer': 1915,
 'defend': 665,
 'attack': 207,
 'refusing': 2181,
 'position': 2059,
 'accuses': 51,
 'western': 2890,
 'jamiefoxx': 1366,
 'christophwaltz': 467,
 'bounty': 326,
 'hunter': 1248,
 'freed': 1026,
 'slave': 2467,
 'sets': 2407,
 'brutal': 357,
 'mississippi': 1790,
 'plantation': 2037,
 'owner': 1947,
 'shelleyduvall': 2425,
 'dannylloyd': 623,
 'heads': 1175,
 'spiritual': 2512,
 'presence': 2076,
 'influences': 1289,
 'psychic': 2118,
 'sees': 2389,
 'forebodings': 992,
 'isolated': 1337,
 'hotel': 1232,
 'winter': 2914,
 'father': 944,
 'tyronepower': 2770,
 'marlenedietrich': 1670,
 'charleslaughton': 438,
 'british': 349,
 'barrister': 242,
 'surprise': 2595,
 'trial': 2741,
 'tomhardy': 2687,
 'city': 473,
 'guerrilla': 1139,
 'terrorist': 2641,
 'bane': 233,
 'enigmatic': 859,
 'selina': 2393,
 'anarchy': 133,
 'forced': 989,
 'reign': 2187,
 'total': 2710,
 'annihilation': 154,
 'imposed': 1267,
 'exile': 904,
 'andrewstanton': 139,
 'benburtt': 272,
 'elissaknight': 825,
 'jeffgarlin': 1387,
 'ultimately': 2772,
 'decide': 657,
 'collecting': 500,
 'robot': 2279,
 'inadvertently': 1273,
 'embarks': 834,
 'mankind': 1656,
 'small': 2474,
 'waste': 2875,
 'fate': 943,
 'distant': 736,
 'sammendes': 2330,
 'annettebening': 152,
 'thorabirch': 2659,
 'sexually': 2414,
 'suburban': 2574,
 'becoming': 258,
 'infatuated': 1285,
 'best': 279,
 'crisis': 590,
 'daughter': 629,
 'mid': 1767,
 'sergioleone': 2401,
 'jameswoods': 1365,
 'elizabethmcgovern': 827,
 'lower': 1619,
 'east': 797,
 'side': 2441,
 'era': 870,
 'returns': 2222,
 'confront': 542,
 'prohibition': 2107,
 'thirty': 2657,
 'later': 1529,
 'manhattan': 1651,
 'ghosts': 1091,
 'regrets': 2186,
 'carriehenn': 400,
 'michaelbiehn': 1754,
 '1979': 19,
 'enough': 861,
 'colonized': 506,
 'lost': 1612,
 'impressive': 1268,
 'firepower': 972,
 'alien': 108,
 'contact': 552,
 'orsonwelles': 1937,
 'josephcotten': 1456,
 'dorothycomingore': 761,
 'agnesmoorehead': 83,
 'publishing': 2123,
 'tycoon': 2766,
 'final': 966,
 'utterance': 2813,
 'news': 1873,
 'reporters': 2204,
 'scramble': 2362,
 'discover': 722,
 'meaning': 1712,
 'carygrant': 406,
 'evamariesaint': 885,
 'jamesmason': 1361,
 'mistaken': 1791,
 'hapless': 1159,
 'advertising': 74,
 'executive': 901,
 'country': 568,
 'pursued': 2126,
 'across': 55,
 'agent': 80,
 'looks': 1608,
 'foreign': 993,
 'kimnovak': 1501,
 'barbarabelgeddes': 236,
 'acrophobia': 54,
 'investigates': 1320,
 'strange': 2556,
 'activities': 57,
 'dangerously': 618,
 'obsessed': 1906,
 'san': 2334,
 'francisco': 1006,
 'detective': 695,
 'suffering': 2582,
 'richardmarquand': 2240,
 'daring': 624,
 'trap': 2734,
 'han': 1155,
 'solo': 2486,
 'without': 2918,
 'falling': 931,
 'jabba': 1340,
 'dispatch': 733,
 'back': 226,
 'endor': 851,
 'hutt': 1252,
 'meanwhile': 1714,
 'melgibson': 1727,
 'jamesrobinson': 1363,
 'seanlawlor': 2372,
 'sandynelson': 2335,
 'edward': 810,
 'english': 857,
 'soldier': 2483,
 'secret': 2380,
 'bride': 343,
 'assaulting': 199,
 'tried': 2745,
 'revolt': 2227,
 'sir': 2458,
 'william': 2901,
 'wallace': 2862,
 'england': 856,
 'executed': 900,
 'harveykeitel': 1171,
 'michaelmadsen': 1762,
 'suspect': 2601,
 'surviving': 2599,
 'begin': 263,
 'simple': 2452,
 'jewelry': 1398,
 'heist': 1185,
 'terribly': 2639,
 'informant': 1290,
 'fredmacmurray': 1021,
 'barbarastanwyck': 238,
 'edwardg': 815,
 'robinson': 2276,
 'arouses': 183,
 'suspicions': 2603,
 'insurance': 1309,
 'representative': 2205,
 'lets': 1567,
 'talked': 2616,
 'investigator': 1322,
 'fraud': 1018,
 'scheme': 2353,
 'darrenaronofsky': 626,
 'jaredleto': 1375,
 'jenniferconnelly': 1389,
 'addictions': 63,
 'deep': 661,
 'drug': 779,
 'induced': 1280,
 'utopias': 2812,
 'shattered': 2423,
 'coney': 535,
 'island': 1336,
 'davidlean': 632,
 'petero': 2012,
 'toole': 2703,
 'alecguinness': 99,
 'anthonyquinn': 161,
 'led': 1555,
 'order': 1930,
 'successfully': 2577,
 'united': 2789,
 'often': 1917,
 'warring': 2871,
 'turks': 2758,
 'arab': 173,
 'tribes': 2743,
 'lawrence': 1541,
 'diverse': 740,
 'carlmiller': 394,
 'ednapurviance': 808,
 'jackiecoogan': 1343,
 'jeopardy': 1391,
 'cares': 392,
 'put': 2129,
 'abandoned': 33,
 'malcolmmcdowell': 1646,
 'patrickmagee': 1973,
 'michaelbates': 1752,
 'britain': 348,
 'solve': 2488,
 'charismatic': 435,
 'problem': 2096,
 ...}

In [40]:
# generating the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)
cosine_sim

array([[1.        , 0.15789474, 0.13764944, ..., 0.05263158, 0.05263158,
        0.05564149],
       [0.15789474, 1.        , 0.36706517, ..., 0.05263158, 0.05263158,
        0.05564149],
       [0.13764944, 0.36706517, 1.        , ..., 0.04588315, 0.04588315,
        0.04850713],
       ...,
       [0.05263158, 0.05263158, 0.04588315, ..., 1.        , 0.05263158,
        0.05564149],
       [0.05263158, 0.05263158, 0.04588315, ..., 0.05263158, 1.        ,
        0.05564149],
       [0.05564149, 0.05564149, 0.04850713, ..., 0.05564149, 0.05564149,
        1.        ]])

In [41]:
# function that takes in movie title as input and returns the top 10 recommended movies
def recommendations(title, cosine_sim = cosine_sim):
    
    recommended_movies = []
    
    # gettin the index of the movie that matches the title
    idx = indices[indices == title].index[0]

    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    # getting the indexes of the 10 most similar movies
    top_10_indexes = list(score_series.iloc[1:11].index)
    print(top_10_indexes)
    
    # populating the list with the titles of the best 10 matching movies
    for i in top_10_indexes:
        recommended_movies.append(list(df.index)[i])
        
    return recommended_movies

In [42]:
recommendations('Fargo')

[132, 34, 226, 1, 61, 2, 100, 15, 214, 125]

['No Country for Old Men',
 'The Departed',
 'Rope',
 'The Godfather',
 'Reservoir Dogs',
 'The Godfather: Part II',
 'On the Waterfront',
 'Goodfellas',
 'Arsenic and Old Lace',
 'The Big Lebowski']

In [43]:
indices[indices == 'Fargo'].index[0]

128

In [44]:
pd.Series(cosine_sim[indices[indices == 'Fargo'].index[0]])

0      0.132453
1      0.220755
2      0.192450
3      0.105409
4      0.140028
         ...
245    0.048113
246    0.041030
247    0.044151
248    0.044151
249    0.046676
Length: 250, dtype: float64